Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Esimene_2._0.Models;
using System.IO;

namespace Esimene_2._0.Controllers
{
    public class MyController : Controller
    {
        // TODO: muuda ära dataContext
        // datacontexti access võix olla protected, 
        // siis saavad MyController tüüpi kontrollerid seda sama datacontexti kasutada
        protected AednikudEntities db = new AednikudEntities();
        [OutputCache(Duration = 3600, VaryByParam = "id", Location = System.Web.UI.OutputCacheLocation.Any)]
        public ActionResult Content(int? id)
        {
            DataFile df = db.DataFiles.Find(id);
            if (df == null) return HttpNotFound();
            return File(df.Content, df.ContentType);
        }


        protected Person CurrentPerson = null; // siis on hea kohe see PersonObject omale taskusse panna
        protected void CheckPerson()
        {
            if (Request.IsAuthenticated)        // kontrollida vaja vaid siis
                if ((CurrentPerson?.Email ?? "") != User.Identity.Name)    // kui juba ei ole meeles või on vale
                    using (AednikudEntities db = new AednikudEntities())
                    {
                        CurrentPerson = db.People.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                        if (CurrentPerson == null)
                        {
                            using (ApplicationDbContext dba = new ApplicationDbContext())
                            {
                                ApplicationUser u = dba.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                                db.People.Add(CurrentPerson = new Person
                                {
                                    Email = User.Identity.Name,
                                    FirstName = u.FirstName,
                                    LastName = u.LastName,
                                    BirthDate = u.BirthDate
                                });
                                db.SaveChanges();
                            }
                        }
                    }
                else CurrentPerson = null;
        }
        // file - kontrollerisse post-requestiga üles laetud fail
        // oldId - vana faili number, mis baasist kustutada (null - mitte kustutada
        // change - tegevus, mis lisamise ja kustutamise vahel vaja teha
        //  x => {person.PictureId = x; db.SaveChanges();}
        protected void ChangeDataFile(HttpPostedFileBase file, Action<int> change, int? oldId)
        {
            if (file != null && file.ContentLength > 0)
                using (BinaryReader br = new BinaryReader(file.InputStream))
                {
                    DataFile df = new DataFile
                    {
                        Content = br.ReadBytes(file.ContentLength),
                        FileName = file.FileName.Split('\\').Last().Split('/').Last(),
                        ContentType = file.ContentType,
                        Created = DateTime.Now
                    };
                    db.DataFiles.Add(df);
                    db.SaveChanges();
                    change(df.Id);
                    if (oldId.HasValue)
                    {
                        db.DataFiles.Remove(db.DataFiles.Find(oldId.Value));
                        db.SaveChanges();
                    }
                }
        }   }
    public class HomeController : MyController
    {

        //public ViewResult Index (string Otsi)
       
        //{
        //    ViewBag.Otsisõna = Otsi;
        //    db.Posts.Where(X => X.Content.Contains.Otsisõna);
        //    return View(db.Posts.ToList());
        //}
        public ActionResult Index()
        {
                CheckPerson(); //person kontroll
                ViewBag.CurrentPerson = CurrentPerson;
                var posts = db.Posts
                    .OrderByDescending(x => x.Created).Take(10)
                    .ToList();
                ViewBag.Posts = posts;
                return View();
        }

 
        public ActionResult About()
        {
            ViewBag.Message = "Siia lisan oma postitused";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Create()
        {
            ViewBag.Message = "Lisa uus postitus.";

            return View();
        }
     

    }

}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Esimene_2._0.Models;
namespace Esimene_2._0.Models
{
    partial class Person
    {
        public string FullName => $"{FirstName} {LastName}";
        public string OwnerID => FullName;
    }
}

namespace Esimene_2._0.Controllers
{
    
    public class PeopleController : MyController
    {
        //private AednikudEntities db = new AednikudEntities();

        // GET: People
        public ActionResult Index()
        {
            //CheckPerson();
            //if (User.IsInRole("Administrator"))
            //{
                var people = db.People.Include(p => p.DataFile);
                return View(people.ToList());
            //}

            //return RedirectToAction("Index", "Home");
        }



        // GET: People/Details/5
        //public ActionResult Details(int? id)
        //{
        //    CheckPerson();


        //    id = id ?? CurrentPerson.Id;

        //    if (!User.IsInRole("Administrator") && id != CurrentPerson.Id)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    Person person = db.People.Find(id);
        //    if(person==null)
        //    {
        //        return HttpNotFound();
        //    }

        //    return View(person);

        //}
        public ActionResult Details(int? id)
        {
            CheckPerson();
            id = id ?? CurrentPerson.Id;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: People/Create
        public ActionResult Lisa(string email)
        {
            if (email == "") return View("Create");
            ApplicationDbContext dba = new ApplicationDbContext();
            ApplicationUser u = dba.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
            db.People.Add(new Person
            {
                Email = email,
                FirstName = u.FirstName,
                LastName = u.LastName,
                BirthDate = u.BirthDate
            });
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Create()
        {
            return View(new Person { Email = "" });
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,FirstName,LastName,BirthDate")] Person person
           , HttpPostedFileBase file
            )
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                ChangeDataFile(file, x => { person.PictureId = x; db.SaveChanges(); }, null);
                return RedirectToAction("Index");
            }

            
            
            return View(person);
        }

        
        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            CheckPerson();

            id = id ?? CurrentPerson.Id;

            if (!User.IsInRole("Administrator") && id != CurrentPerson.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,FirstName,LastName,BirthDate,PictureId")] Person person, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                ChangeDataFile(file, x => { person.PictureId = x; db.SaveChanges(); }, person.PictureId);
                return RedirectToAction("Index");
            }

            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            CheckPerson();

            id = id ?? CurrentPerson.Id;

            if (!User.IsInRole("Administrator") && id != CurrentPerson.Id)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Esimene_2._0.Models;

namespace Esimene_2._0.Controllers
{
    //[Authorize(Roles = "User, Admin")]



    public class PostsController : MyController
    {        //Lisasin Otsi meetodi
        public ActionResult Otsi(string searching)
        {

            ViewBag.search = searching;
            return View(db.Posts.Where(x => x.Title.Contains(searching) || x.Content.Contains(searching) || searching == null).ToList());
         
        }

        //private AednikudEntities db = new AednikudEntities();

        // GET: Posts
        public ActionResult Index()
        {
            CheckPerson();
            ViewBag.CurrentPerson = CurrentPerson;
            if (User.IsInRole("Administrator"))
            {
                var posts = db.Posts.Include(p => p.DataFile).Include(p => p.Person).Include(p => p.Subject);
                return View(posts.ToList());
            }
            else
            {
                var posts = db.Posts.Include(p => p.DataFile).Include(p => p.Person).Include(p => p.Subject)
                .Where(x => x.OwnerId == CurrentPerson.Id)
              ;

                return View(posts.ToList());
            }
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        public ActionResult Create()
            
        {
            CheckPerson();

            ViewBag.OwnerId = new SelectList(db.People, "Id", "Email", CurrentPerson.Id);
            //ViewBag.OwnerId = CurrentPerson.Id;
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name");
            return View( new Post { Created = DateTime.Now, OwnerId = CurrentPerson.Id});
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OwnerId,Created,SubjectId,PictureId,Title,Content,State")] Post post
            , HttpPostedFileBase file)
        {
            //if(NewSubject != "")
            //{
            //    Subject subject = new Subject { Name = NewSubject };
            //    db.Subjects.Add(subject);
            //    db.SaveChanges();
            //    post.SubjectId = subject.Id;
            //}
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();
                ChangeDataFile(file, x => { post.PictureId = x; db.SaveChanges(); }, null);
                return RedirectToAction("Index");
            }

            CheckPerson();
            ViewBag.OwnerId = new SelectList(db.People, "Id", "Email", post.OwnerId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", post.SubjectId);
            return View(post);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //Post post = db.Posts.Find(id);
            //if (post == null)
            //{
            //    return HttpNotFound();
            //}

            CheckPerson();

            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("Administrator") || post.OwnerId == CurrentPerson.Id)

            {

                ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", post.SubjectId);
                return View(post);
            }
            else return RedirectToAction("Index");
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerId,Created,SubjectId,PictureId,Title,Content,Access,State")] Post post
            , HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                ChangeDataFile(file, x => { post.PictureId = x; db.SaveChanges(); }, post.PictureId);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           

            ViewBag.SubjectId = new SelectList(db.Subjects, "Id", "Name", post.SubjectId);
            return View(post);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            CheckPerson();

            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }

            if (!User.IsInRole("Administrator") || post.OwnerId == CurrentPerson.Id)
            {

                ViewBag.Delete = new SelectList(db.Subjects, "Id", "Name", post.SubjectId);
                return View(post);
            }
            else return RedirectToAction("Index");
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Posts/Create.cshtml
@model Esimene_2._0.Models.Post

@{
    ViewBag.Title = "Create";
}
    <style>
        body {
            background: -webkit-linear-gradient(left, #ffffff, #a8a8a9);
        }
    </style>
<h2 style= "font-family: 'Berlin Sans FB'">Siin lehel saab lisada uue postituse</h2>


@using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.OwnerId, "Postituse lisaja", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Created, "Postituse kuupäev", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SubjectId, "Kategooria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SubjectId", null, "Vali kategooria", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SubjectId, "Vali teema", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Title, "Nimi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, "Sisu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "required", style = "width: 100%; max-width: 100%;" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.Label("NewSubject", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("NewSubject", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Access, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.Access, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Access, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Access, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>*@

    @*<div class="form-group">
            <label for="file" class="control-label col-md-2">Lae üles postituse pilt</label>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control"/>
                <img id="pilt"src='@Url.Action("Content","Datafile", new { id = Model.Subject })'width="100"/>
            </div>
        </div>*@
    <div class="form-group">
        <label class="control-label col-md-2">Lisa pilt</label>
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
            <img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
            @Html.HiddenFor(x => x.PictureId)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta" class="btn btn-success" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Tagasi nimekirja", "Index")
        </div>
    </div>

</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#datafile').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
   $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
   });</script>

Views/Posts/Edit.cshtml
@model Esimene_2._0.Models.Post

@{
    ViewBag.Title = "Edit";
}
    <style>
        body {
            background: -webkit-linear-gradient(left, #ffffff, #a8a8a9);
        }
    </style>
<h2 style= "font-family: 'Berlin Sans FB'">Siin lehel saab muuta postitust</h2>


@using (Html.BeginForm("Edit", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.OwnerId)


    <div class="form-group">
        @Html.LabelFor(model => model.SubjectId, "Kategooria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.PictureId, "PictureId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PictureId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PictureId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Title, "Nimi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Content, "Sisu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Created, "Postituse kuupäev", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">@(Model.PictureId == null ? "Lisa" : "Muuda") pilt</label>
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
            <img src="@Url.Action("Content", "My", new { id=Model.PictureId })" height="120" id="datafile" />
            @Html.HiddenFor(x => x.PictureId)
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.Access, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Access, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Access, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta muudatused" class="btn btn-success" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink("Tagasi nimekirja", "Index")
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script>
function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#datafile').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
   $(document).ready(function () {
        $("#file").change(function () {
            readURL(this);
        });
   });</script>

Views/Posts/Otsi.cshtml
@model IEnumerable<Esimene_2._0.Models.Post>

<br />
<br />
@using (Html.BeginForm("Otsi", "Posts", FormMethod.Get))
{
    @Html.TextBox("searching")
    <input type="submit" value="Otsi lehelt" />

}
<br />

<table class="table table-striped">
    <thread>
        <tr>
            <th>Pilt</th>
            <th>Nimi</th>
            <th>Kategooria</th>
            <th>Sisu</th>
            @*<th>Created</th>*@
            <th>Postitaja</th>

        </tr>
    </thread>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3" style="color:red">
                    Ei leidnud midagi!
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td><img src="@Url.Action("Content", "My", new { id = item.PictureId })" height="120" /></td>
                    <td>@Html.ActionLink(item.Title, "Details", "Posts", new { id = item.Id }, null)</td>
                    <td>@item.Subject.Name</td>
                    <td>@item.Content</td>
                    @*<th>@item.Created</th>*@
                    <td>
                        @Html.ActionLink(item.Person.FullName, "Details", "People", new { id = item.OwnerId }, null)

                        <img class="img-circle" src="@Url.Action("Content", "My", new { id = item.Person.PictureId })" height="50" />
                    </td>


                </tr>
            }
        }
        @Html.ActionLink("Tagasi nimekirja", "Otsi", "Posts")
    <br />
    </tbody>
    <br />
</table>